/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using XperiencesAI.SDK.Api;
using XperiencesAI.SDK.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace XperiencesAI.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing ChatApi
    /// </summary>
    public sealed class ChatApiTests : ApiTestsBase
    {
        private readonly IChatApi _instance;

        public ChatApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IChatApi>();
        }

        /// <summary>
        /// Test CreateChatApiV1ChatChatsPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateChatApiV1ChatChatsPostAsyncTest()
        {
            ConversationCreate conversationCreate = default!;
            var response = await _instance.CreateChatApiV1ChatChatsPostAsync(conversationCreate);
            var model = response.Ok();
            Assert.IsType<ConversationResponse>(model);
        }

        /// <summary>
        /// Test CreateMessageApiV1ChatChatsChatIdMessagesPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateMessageApiV1ChatChatsChatIdMessagesPostAsyncTest()
        {
            string chatId = default!;
            MessageCreate messageCreate = default!;
            var response = await _instance.CreateMessageApiV1ChatChatsChatIdMessagesPostAsync(chatId, messageCreate);
            var model = response.Ok();
            Assert.IsType<MessageResponse>(model);
        }

        /// <summary>
        /// Test GetChatApiV1ChatChatsChatIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetChatApiV1ChatChatsChatIdGetAsyncTest()
        {
            string chatId = default!;
            var response = await _instance.GetChatApiV1ChatChatsChatIdGetAsync(chatId);
            var model = response.Ok();
            Assert.IsType<ConversationResponse>(model);
        }
    }
}
