/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using XperiencesAI.SDK.Api;
using XperiencesAI.SDK.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace XperiencesAI.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing UsersApi
    /// </summary>
    public sealed class UsersApiTests : ApiTestsBase
    {
        private readonly IUsersApi _instance;

        public UsersApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IUsersApi>();
        }

        /// <summary>
        /// Test CreateUserApiV1UsersPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateUserApiV1UsersPostAsyncTest()
        {
            UserCreate userCreate = default!;
            var response = await _instance.CreateUserApiV1UsersPostAsync(userCreate);
            var model = response.Ok();
            Assert.IsType<UserResponse>(model);
        }

        /// <summary>
        /// Test DeleteUserApiV1UsersUserIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteUserApiV1UsersUserIdDeleteAsyncTest()
        {
            string userId = default!;
            await _instance.DeleteUserApiV1UsersUserIdDeleteAsync(userId);
        }

        /// <summary>
        /// Test GetUserApiV1UsersUserIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetUserApiV1UsersUserIdGetAsyncTest()
        {
            string userId = default!;
            var response = await _instance.GetUserApiV1UsersUserIdGetAsync(userId);
            var model = response.Ok();
            Assert.IsType<UserResponse>(model);
        }

        /// <summary>
        /// Test UpdateUserApiV1UsersUserIdPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateUserApiV1UsersUserIdPutAsyncTest()
        {
            string userId = default!;
            UserUpdate userUpdate = default!;
            var response = await _instance.UpdateUserApiV1UsersUserIdPutAsync(userId, userUpdate);
            var model = response.Ok();
            Assert.IsType<UserResponse>(model);
        }
    }
}
