/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using XperiencesAI.SDK.Model;
using XperiencesAI.SDK.Client;
using System.Reflection;

namespace XperiencesAI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing AgentStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgentStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgentStatus
        //private AgentStatus instance;

        public AgentStatusTests()
        {
            // TODO uncomment below to create an instance of AgentStatus
            //instance = new AgentStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgentStatus
        /// </summary>
        [Fact]
        public void AgentStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgentStatus
            //Assert.IsType<AgentStatus>(instance);
        }
    }
}
