/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using XperiencesAI.SDK.Model;
using XperiencesAI.SDK.Client;
using System.Reflection;

namespace XperiencesAI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ConversationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConversationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConversationResponse
        //private ConversationResponse instance;

        public ConversationResponseTests()
        {
            // TODO uncomment below to create an instance of ConversationResponse
            //instance = new ConversationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConversationResponse
        /// </summary>
        [Fact]
        public void ConversationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConversationResponse
            //Assert.IsType<ConversationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'FunctionCalls'
        /// </summary>
        [Fact]
        public void FunctionCallsTest()
        {
            // TODO unit test for the property 'FunctionCalls'
        }
    }
}
