/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using XperiencesAI.SDK.Model;
using XperiencesAI.SDK.Client;
using System.Reflection;

namespace XperiencesAI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ConversationCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConversationCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConversationCreate
        //private ConversationCreate instance;

        public ConversationCreateTests()
        {
            // TODO uncomment below to create an instance of ConversationCreate
            //instance = new ConversationCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConversationCreate
        /// </summary>
        [Fact]
        public void ConversationCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConversationCreate
            //Assert.IsType<ConversationCreate>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'MetaData'
        /// </summary>
        [Fact]
        public void MetaDataTest()
        {
            // TODO unit test for the property 'MetaData'
        }
    }
}
