/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using XperiencesAI.SDK.Model;
using XperiencesAI.SDK.Client;
using System.Reflection;

namespace XperiencesAI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing HTTPValidationError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HTTPValidationErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HTTPValidationError
        //private HTTPValidationError instance;

        public HTTPValidationErrorTests()
        {
            // TODO uncomment below to create an instance of HTTPValidationError
            //instance = new HTTPValidationError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HTTPValidationError
        /// </summary>
        [Fact]
        public void HTTPValidationErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" HTTPValidationError
            //Assert.IsType<HTTPValidationError>(instance);
        }

        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }
    }
}
