/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using XperiencesAI.SDK.Model;
using XperiencesAI.SDK.Client;
using System.Reflection;

namespace XperiencesAI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing MessageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MessageResponse
        //private MessageResponse instance;

        public MessageResponseTests()
        {
            // TODO uncomment below to create an instance of MessageResponse
            //instance = new MessageResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessageResponse
        /// </summary>
        [Fact]
        public void MessageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MessageResponse
            //Assert.IsType<MessageResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'AudioUrl'
        /// </summary>
        [Fact]
        public void AudioUrlTest()
        {
            // TODO unit test for the property 'AudioUrl'
        }
    }
}
