/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using XperiencesAI.SDK.Model;
using XperiencesAI.SDK.Client;
using System.Reflection;

namespace XperiencesAI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing MessageRole
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageRoleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MessageRole
        //private MessageRole instance;

        public MessageRoleTests()
        {
            // TODO uncomment below to create an instance of MessageRole
            //instance = new MessageRole();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessageRole
        /// </summary>
        [Fact]
        public void MessageRoleInstanceTest()
        {
            // TODO uncomment below to test "IsType" MessageRole
            //Assert.IsType<MessageRole>(instance);
        }
    }
}
