/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using XperiencesAI.SDK.Model;
using XperiencesAI.SDK.Client;
using System.Reflection;

namespace XperiencesAI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing TextRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TextRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TextRequest
        //private TextRequest instance;

        public TextRequestTests()
        {
            // TODO uncomment below to create an instance of TextRequest
            //instance = new TextRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TextRequest
        /// </summary>
        [Fact]
        public void TextRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TextRequest
            //Assert.IsType<TextRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'ConversationId'
        /// </summary>
        [Fact]
        public void ConversationIdTest()
        {
            // TODO unit test for the property 'ConversationId'
        }

        /// <summary>
        /// Test the property 'MetaData'
        /// </summary>
        [Fact]
        public void MetaDataTest()
        {
            // TODO unit test for the property 'MetaData'
        }
    }
}
