/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using XperiencesAI.SDK.Model;
using XperiencesAI.SDK.Client;
using System.Reflection;

namespace XperiencesAI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing UserResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserResponse
        //private UserResponse instance;

        public UserResponseTests()
        {
            // TODO uncomment below to create an instance of UserResponse
            //instance = new UserResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserResponse
        /// </summary>
        [Fact]
        public void UserResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserResponse
            //Assert.IsType<UserResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'IsSuperuser'
        /// </summary>
        [Fact]
        public void IsSuperuserTest()
        {
            // TODO unit test for the property 'IsSuperuser'
        }
    }
}
