// <auto-generated>
/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using XperiencesAI.SDK.Client;

namespace XperiencesAI.SDK.Model
{
    /// <summary>
    /// Schema for updating an agent.
    /// </summary>
    public partial class AgentUpdate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentUpdate" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="description">description</param>
        /// <param name="status">status</param>
        /// <param name="promptTemplate">promptTemplate</param>
        /// <param name="varConfiguration">varConfiguration</param>
        [JsonConstructor]
        public AgentUpdate(Option<string?> name = default, Option<string?> description = default, Option<AgentStatus?> status = default, Option<string?> promptTemplate = default, Option<Dictionary<string, Object>?> varConfiguration = default)
        {
            NameOption = name;
            DescriptionOption = description;
            StatusOption = status;
            PromptTemplateOption = promptTemplate;
            VarConfigurationOption = varConfiguration;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AgentStatus?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public AgentStatus? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of PromptTemplate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PromptTemplateOption { get; private set; }

        /// <summary>
        /// Gets or Sets PromptTemplate
        /// </summary>
        [JsonPropertyName("prompt_template")]
        public string? PromptTemplate { get { return this.PromptTemplateOption; } set { this.PromptTemplateOption = new(value); } }

        /// <summary>
        /// Used to track the state of VarConfiguration
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>?> VarConfigurationOption { get; private set; }

        /// <summary>
        /// Gets or Sets VarConfiguration
        /// </summary>
        [JsonPropertyName("configuration")]
        public Dictionary<string, Object>? VarConfiguration { get { return this.VarConfigurationOption; } set { this.VarConfigurationOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AgentUpdate {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  PromptTemplate: ").Append(PromptTemplate).Append("\n");
            sb.Append("  VarConfiguration: ").Append(VarConfiguration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AgentUpdate" />
    /// </summary>
    public class AgentUpdateJsonConverter : JsonConverter<AgentUpdate>
    {
        /// <summary>
        /// Deserializes json to <see cref="AgentUpdate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AgentUpdate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> description = default;
            Option<AgentStatus?> status = default;
            Option<string?> promptTemplate = default;
            Option<Dictionary<string, Object>?> varConfiguration = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<AgentStatus?>(AgentStatusValueConverter.FromStringOrDefault(statusRawValue));
                            break;
                        case "prompt_template":
                            promptTemplate = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "configuration":
                            varConfiguration = new Option<Dictionary<string, Object>?>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            return new AgentUpdate(name, description, status, promptTemplate, varConfiguration);
        }

        /// <summary>
        /// Serializes a <see cref="AgentUpdate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="agentUpdate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AgentUpdate agentUpdate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, agentUpdate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AgentUpdate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="agentUpdate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AgentUpdate agentUpdate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (agentUpdate.NameOption.IsSet)
                if (agentUpdate.NameOption.Value != null)
                    writer.WriteString("name", agentUpdate.Name);
                else
                    writer.WriteNull("name");

            if (agentUpdate.DescriptionOption.IsSet)
                if (agentUpdate.DescriptionOption.Value != null)
                    writer.WriteString("description", agentUpdate.Description);
                else
                    writer.WriteNull("description");

            if (agentUpdate.StatusOption.IsSet)
                if (agentUpdate.StatusOption!.Value != null)
                {
                    var statusRawValue = AgentStatusValueConverter.ToJsonValue(agentUpdate.StatusOption.Value!.Value);
                    writer.WriteString("status", statusRawValue);
                }
                else
                    writer.WriteNull("status");
            if (agentUpdate.PromptTemplateOption.IsSet)
                if (agentUpdate.PromptTemplateOption.Value != null)
                    writer.WriteString("prompt_template", agentUpdate.PromptTemplate);
                else
                    writer.WriteNull("prompt_template");

            if (agentUpdate.VarConfigurationOption.IsSet)
                if (agentUpdate.VarConfigurationOption.Value != null)
                {
                    writer.WritePropertyName("configuration");
                    JsonSerializer.Serialize(writer, agentUpdate.VarConfiguration, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("configuration");
        }
    }
}
