// <auto-generated>
/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using XperiencesAI.SDK.Client;

namespace XperiencesAI.SDK.Model
{
    /// <summary>
    /// Schema for text processing request.
    /// </summary>
    public partial class TextRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TextRequest" /> class.
        /// </summary>
        /// <param name="text">Text input from the user</param>
        /// <param name="conversationId">conversationId</param>
        /// <param name="metaData">Additional meta_data for the request</param>
        [JsonConstructor]
        public TextRequest(string text, Option<string?> conversationId = default, Option<Dictionary<string, Object>?> metaData = default)
        {
            Text = text;
            ConversationIdOption = conversationId;
            MetaDataOption = metaData;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Text input from the user
        /// </summary>
        /// <value>Text input from the user</value>
        [JsonPropertyName("text")]
        public string Text { get; set; }

        /// <summary>
        /// Used to track the state of ConversationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConversationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConversationId
        /// </summary>
        [JsonPropertyName("conversation_id")]
        public string? ConversationId { get { return this.ConversationIdOption; } set { this.ConversationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of MetaData
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>?> MetaDataOption { get; private set; }

        /// <summary>
        /// Additional meta_data for the request
        /// </summary>
        /// <value>Additional meta_data for the request</value>
        [JsonPropertyName("meta_data")]
        public Dictionary<string, Object>? MetaData { get { return this.MetaDataOption; } set { this.MetaDataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TextRequest {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  ConversationId: ").Append(ConversationId).Append("\n");
            sb.Append("  MetaData: ").Append(MetaData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TextRequest" />
    /// </summary>
    public class TextRequestJsonConverter : JsonConverter<TextRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="TextRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TextRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> text = default;
            Option<string?> conversationId = default;
            Option<Dictionary<string, Object>?> metaData = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "text":
                            text = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "conversation_id":
                            conversationId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "meta_data":
                            metaData = new Option<Dictionary<string, Object>?>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!text.IsSet)
                throw new ArgumentException("Property is required for class TextRequest.", nameof(text));

            if (text.IsSet && text.Value == null)
                throw new ArgumentNullException(nameof(text), "Property is not nullable for class TextRequest.");

            if (metaData.IsSet && metaData.Value == null)
                throw new ArgumentNullException(nameof(metaData), "Property is not nullable for class TextRequest.");

            return new TextRequest(text.Value!, conversationId, metaData);
        }

        /// <summary>
        /// Serializes a <see cref="TextRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="textRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TextRequest textRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, textRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TextRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="textRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TextRequest textRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (textRequest.Text == null)
                throw new ArgumentNullException(nameof(textRequest.Text), "Property is required for class TextRequest.");

            if (textRequest.MetaDataOption.IsSet && textRequest.MetaData == null)
                throw new ArgumentNullException(nameof(textRequest.MetaData), "Property is required for class TextRequest.");

            writer.WriteString("text", textRequest.Text);

            if (textRequest.ConversationIdOption.IsSet)
                if (textRequest.ConversationIdOption.Value != null)
                    writer.WriteString("conversation_id", textRequest.ConversationId);
                else
                    writer.WriteNull("conversation_id");

            if (textRequest.MetaDataOption.IsSet)
            {
                writer.WritePropertyName("meta_data");
                JsonSerializer.Serialize(writer, textRequest.MetaData, jsonSerializerOptions);
            }
        }
    }
}
