// <auto-generated>
/*
 * Xperiences API
 *
 * API for VR mentoring experiences
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@xperiences.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using XperiencesAI.SDK.Client;

namespace XperiencesAI.SDK.Model
{
    /// <summary>
    /// Schema for creating a new user.
    /// </summary>
    public partial class UserCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCreate" /> class.
        /// </summary>
        /// <param name="email">User&#39;s email address</param>
        /// <param name="fullName">User&#39;s full name</param>
        /// <param name="password">User&#39;s password</param>
        /// <param name="isActive">Whether the user is active (default to true)</param>
        /// <param name="isSuperuser">Whether the user is a superuser (default to false)</param>
        [JsonConstructor]
        public UserCreate(string email, string fullName, string password, Option<bool?> isActive = default, Option<bool?> isSuperuser = default)
        {
            Email = email;
            FullName = fullName;
            Password = password;
            IsActiveOption = isActive;
            IsSuperuserOption = isSuperuser;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// User&#39;s email address
        /// </summary>
        /// <value>User&#39;s email address</value>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// User&#39;s full name
        /// </summary>
        /// <value>User&#39;s full name</value>
        [JsonPropertyName("full_name")]
        public string FullName { get; set; }

        /// <summary>
        /// User&#39;s password
        /// </summary>
        /// <value>User&#39;s password</value>
        [JsonPropertyName("password")]
        public string Password { get; set; }

        /// <summary>
        /// Used to track the state of IsActive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsActiveOption { get; private set; }

        /// <summary>
        /// Whether the user is active
        /// </summary>
        /// <value>Whether the user is active</value>
        [JsonPropertyName("is_active")]
        public bool? IsActive { get { return this.IsActiveOption; } set { this.IsActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsSuperuser
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsSuperuserOption { get; private set; }

        /// <summary>
        /// Whether the user is a superuser
        /// </summary>
        /// <value>Whether the user is a superuser</value>
        [JsonPropertyName("is_superuser")]
        public bool? IsSuperuser { get { return this.IsSuperuserOption; } set { this.IsSuperuserOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserCreate {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  FullName: ").Append(FullName).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  IsSuperuser: ").Append(IsSuperuser).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Password (string) minLength
            if (this.Password != null && this.Password.Length < 8)
            {
                yield return new ValidationResult("Invalid value for Password, length must be greater than 8.", new [] { "Password" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UserCreate" />
    /// </summary>
    public class UserCreateJsonConverter : JsonConverter<UserCreate>
    {
        /// <summary>
        /// Deserializes json to <see cref="UserCreate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UserCreate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> email = default;
            Option<string?> fullName = default;
            Option<string?> password = default;
            Option<bool?> isActive = default;
            Option<bool?> isSuperuser = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "full_name":
                            fullName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "password":
                            password = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "is_active":
                            isActive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "is_superuser":
                            isSuperuser = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class UserCreate.", nameof(email));

            if (!fullName.IsSet)
                throw new ArgumentException("Property is required for class UserCreate.", nameof(fullName));

            if (!password.IsSet)
                throw new ArgumentException("Property is required for class UserCreate.", nameof(password));

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class UserCreate.");

            if (fullName.IsSet && fullName.Value == null)
                throw new ArgumentNullException(nameof(fullName), "Property is not nullable for class UserCreate.");

            if (password.IsSet && password.Value == null)
                throw new ArgumentNullException(nameof(password), "Property is not nullable for class UserCreate.");

            if (isActive.IsSet && isActive.Value == null)
                throw new ArgumentNullException(nameof(isActive), "Property is not nullable for class UserCreate.");

            if (isSuperuser.IsSet && isSuperuser.Value == null)
                throw new ArgumentNullException(nameof(isSuperuser), "Property is not nullable for class UserCreate.");

            return new UserCreate(email.Value!, fullName.Value!, password.Value!, isActive, isSuperuser);
        }

        /// <summary>
        /// Serializes a <see cref="UserCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UserCreate userCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, userCreate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UserCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UserCreate userCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (userCreate.Email == null)
                throw new ArgumentNullException(nameof(userCreate.Email), "Property is required for class UserCreate.");

            if (userCreate.FullName == null)
                throw new ArgumentNullException(nameof(userCreate.FullName), "Property is required for class UserCreate.");

            if (userCreate.Password == null)
                throw new ArgumentNullException(nameof(userCreate.Password), "Property is required for class UserCreate.");

            writer.WriteString("email", userCreate.Email);

            writer.WriteString("full_name", userCreate.FullName);

            writer.WriteString("password", userCreate.Password);

            if (userCreate.IsActiveOption.IsSet)
                writer.WriteBoolean("is_active", userCreate.IsActiveOption.Value!.Value);

            if (userCreate.IsSuperuserOption.IsSet)
                writer.WriteBoolean("is_superuser", userCreate.IsSuperuserOption.Value!.Value);
        }
    }
}
